### ISSUE TITLE
Not rendering data in list while reading from csv file.

### ISSUE THREAD

**Issue by pakzy** [tlienart/FranklinFAQ#1]
Hi,

I followed documentation but i don't know where i am getting wrong.

1) csv file is in _assets. It has 3 rows(used same file which is used here.)

2) Added code in config.md
@def members_from_csv = eachrow(readdlm("_assets/members.csv", ',', skipstart=1))

3) Used code in file.
~~~
<ul>
{{for (name, alias) in members_from_csv}}
  <li>
    <a href="https://github.com/{{alias}}">{{name}}</a>
  </li>
{{end}}
</ul>
~~~

4) Getting blank output
<ul>
<li></li>
<li></li>
<li></li>
</ul>

Please let me know what i am missing.

**Comment by tlienart** [comment]
Hello @pakzy which version of Franklin do you use please? it may be that you're on an older version where just writing `{{alias}}` in a `{{for...}}` didn't work, you had to write explicitly `{{fill alias}}`. 

(in that case you would see some warning messages in your repl)

**Comment by pakzy** [comment]
Hi tlienart,

You are right, its working with {{fill alias}}. Thanks for saving my day. :)

**Comment by tlienart** [comment]
Cool! so if you update, it should also work like you had written it earlier. I'll close the issue now but do open another one if you encounter more problems!
